# Generated by Django 2.1.3 on 2018-11-02 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifactdetails',
            old_name='added_to_mus_date',
            new_name='added_to_museum_on_date',
        ),
        migrations.AlterField(
            model_name='artifactdetails',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
