# Generated by Django 2.1.3 on 2018-11-02 09:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('details', '0002_auto_20181102_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtifactDetails',
            new_name='ArtifactDetail',
        ),
    ]
