# Generated by Django 2.1.3 on 2018-11-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20181102_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifactdetail',
            old_name='created_date',
            new_name='excavated_date',
        ),
        migrations.RemoveField(
            model_name='artifactdetail',
            name='added_to_museum_on_date',
        ),
        migrations.AddField(
            model_name='artifactdetail',
            name='artifact_year',
            field=models.CharField(default='NA', max_length=40),
        ),
    ]
