# Generated by Django 2.1.3 on 2018-11-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_auto_20181102_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactdetail',
            name='artifact_image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
